[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Leonardo Benicio", email = "hi@lbenicio.dev"}]
dynamic = ["version", "description"]
