name: Publish Docker image to GHCR

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: publish-ghcr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildx (push image)
        run: |
          docker buildx build \
          --platform linux/arm64/v8,linux/amd64 \
          --tag ghcr.io/${{ github.repository }}:latest \
          --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
          --file ./Dockerfile \
          --output type=image,push=true .
